Update Linux instructions
servo/download.servo.org pull request #13
Opened 2016-12-30 00:22 UTC by UK992

2017-01-05 03:38 UTC, aneeshusa requested changes
One nit.

2017-01-05 03:38 UTC, aneeshusa commented on index.html
> +                    <li>Execute the `./servo` script to run Servo</li>
`./servo` isn't a script but the actual executable, so remove `the` and `script` from this line.

2017-01-05 03:48 UTC, UK992 commented
done

2017-01-05 03:58 UTC, aneeshusa approved these changes
Thanks for the PR, LGTM! Homu is [not yet enabled](https://github.com/servo/saltfs/pull/574) for this repo, so I can't merge this yet.

2017-01-22 17:40 UTC, jdm commented
cc @edunham 
We're missing homu and/or other developers in the teams allowed to merge things in this repository.

2017-01-22 17:45 UTC, aneeshusa commented
@jdm that work is already underway, see https://github.com/servo/saltfs/pull/574 and #6, this repo just needs a .travis.yml file.

2017-03-27 22:17 UTC, merged